# Se crea el servicio
apiVersion: v1
kind: Service

# Nombre del servicio y espacio de Kubernetes donde crear el servicio:
metadata:
  name: sentiment-classification-service
  namespace: sentiment-classification

spec:
  # Pods a los que aplicar el servicio: los pods deben tener como etiqueta la clave y el valor especificados en este campo
  selector:
    app: sentiment-classification-pods

  # Dos puertos que tendrá el servicio (3000 para la API REST de TensorFlow Serving; y 3001 para la aplicación web). Evidentemente cada puerto
  # debe apuntar a los puertos expuestos en las imágenes (8501 en la imagen de TensorFlow Serving y 8502 en la imagen de Streamlit)
  ports:
    - name: backend
      protocol: "TCP"
      port: 3000
      targetPort: 8501
      nodePort: 30300
    - name: frontend
      protocol: "TCP"
      port: 3001
      targetPort: 8502
      nodePort: 30301

  # Tipo del servicio: Expone el servicio al exterior del cluster balanceando el tráfico entre los pods disponibles
  type: LoadBalancer

---

# Se crea el despliegue
apiVersion: apps/v1
kind: Deployment

# Nombre del despliegue y espacio de Kubernetes donde crear el servicio:
metadata:
  name: sentiment-classification-deployment
  namespace: sentiment-classification

spec:
  # Pods a los que aplicar el despliegue: los pods deben tener como etiqueta la clave y el valor especificados en este campo
  selector:
    matchLabels:
      app: sentiment-classification-pods

  # El despliegue de Kubernetes tendrá 3 replicas o pods
  replicas: 3

  # Plantilla del despliegue en la que se define la parte de los 'pods'
  template:

    # En los metadatos se definen las etiquetas de los 'pods'. Deben tener la misma clave y valor que la parte 'selector' del
    # despliegue y el servicio para que ambos estén enlazados con los pods y viceversa
    metadata:
      labels:
        app: sentiment-classification-pods

    # Cada 'pod' tiene dos contenedores (uno con la imagen de la API de TensorFlow Serving y otro con la imagen de la interfaz
    # gráfica de Streamlit) con los puertos expuestos en cada una de las imágenes (8501 para la API REST y 8502 para la aplicación web)
    spec:
      containers:
        - name: tfserving-sentiment-classification-container
          image: valderas7/tf_serving_sentiment_classifier:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
        - name: streamlit-sentiment-classification-container
          image: valderas7/streamlit_sentiment_classifier:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8502